[package]
name = "reth-beacon-consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-ethereum-consensus.workspace = true
reth-provider.workspace = true
reth-tasks.workspace = true
reth-static-file.workspace = true
reth-engine-primitives.workspace = true
reth-node-types.workspace = true

# ethereum
alloy-primitives.workspace = true
alloy-eips.workspace = true

# metrics
reth-metrics.workspace = true
metrics.workspace = true

# misc
tracing.workspace = true
schnellru.workspace = true

[dev-dependencies]

[features]
optimism = []
